# Site settings
title: Women in OSS
icon: "favicon.ico"
description: >-
  A website to support women participation in open source projects.
baseurl: "" # Set this if your site is in a subdirectory, e.g., "/blog"
url: "https://womeninoss.com" # Change to your domain

# Markdown settings
markdown: kramdown

include:
  - image
  - posts
  - tools

# Exclude files from the build
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
